--Movies
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(1, 'Joker', 'In Gotham City, mentally-troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: "The Joker".', 'Crime, Drama, Thriller', '8.9/10', 'zAGVQLHvwOY', 'Todd Phillips', 'Joaquin Phoenix, Robert De Niro', 'https://cenapop.uol.com.br/wordpress/wp-content/uploads/2019/04/joker-filme.jpg', 'https://wallpapercave.com/wp/wp4714656.jpg', NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(3, 'Countdown', 'When a nurse downloads an app that claims to predict the moment a person will die, it tells her she only has three days to live. With the clock ticking and a figure haunting her, she must find a way to save her life before time runs out.', 'Horror, Thriller', '4,8/10', 'TZsgNH17_X4', 'Justin Dec', 'Elizabeth Lail, Jordan Calloway, Talitha Eliana Bateman', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTYcSN_I6vlfcScAk2JRIxREnBhIJMWG3k1L-wIde5UhRUTtulM', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(4, 'The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Drama', '9,3/10', '6hB3S9bIaco', 'Frank Darabont', 'Tim Robbins, Morgan Freeman, Bob Gunton', 'https://static-movie.a.88cdn.com/e98b57018bcf8699118b4a31cd3467d9?imageView2/2/q/85/interlace/1/format/gif', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(5, 'The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.
', 'Crime, Drama', '9,2/10', 'sY1S34973zA', 'Francis Ford Coppola', 'Marlon Brando, Al Pacino, James Caan', 'https://hugecrimedramamovieguy.files.wordpress.com/2018/10/cropped-godfather.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(6, 'The Godfather: Part II', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.
', 'Crime, Drama', '9,0/10', '9O1Iy9od7-A', 'Francis Ford Coppola', 'Al Pacino, Robert De Niro, Robert Duvall', 'https://i.pinimg.com/originals/68/a3/6c/68a36c2091d54e9a8feca453f10da0de.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(7, 'The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.
', 'Action, Crime, Drama', '9,0/10', 'EXeTwQWrcwY', 'Christopher Nolan', 'Christian Bale, Heath Ledger, Aaron Eckhart', 'https://i.pinimg.com/originals/09/65/81/09658109acfea0e248a63932337d8e6a.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(8, '12 Angry Men', 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.
', 'Drama', '8,9/10', '_13J_9B5jEk', 'Sidney Lumet', 'Henry Fonda, Lee J. Cobb, Martin Balsam', 'https://www.zhihutai.com/p/http://mmbiz.qpic.cn/mmbiz_jpg/GVMRCtjdIkuobogBR96g3xHem5ukpSO57jia2xTN2PJ8Y7d2dxN1yDTtgG7zVjZ3BmPG00sNMCdxd5ibEwFVeK5w/0?wx_fmt=jpeg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(9, 'Schindler''s List', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.
', 'Biography, Drama, History', '8,9/10', 'mxphAlJID9U', 'Steven Spielberg', ' Liam Neeson, Ralph Fiennes', 'http://www.kultunaut.dk/images/film/7095767/plakat.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(10, 'The Lord of the Rings: The Return of the King', 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.
', 'Adventure, Drama, Fantasy', '8,9/10', 'r5X-hFf6Bwo', 'Peter Jackson', 'Elijah Wood, Viggo Mortensen, Ian McKellen', 'http://n.sinaimg.cn/sinacn20108/280/w1080h1600/20190919/e0c7-ietnfsq7524344.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(11, 'Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.
', 'Crime, Drama', '8,9/10', 's7EdQ4FqbhY', 'Quentin Tarantino', 'John Travolta, Uma Thurman, Samuel L. Jackson', 'https://toloka.to/photos/190528200847240915_f0_0.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(12, 'Il buono, il brutto, il cattivo', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.
', 'Western', '8,8/10', 'WCN5JJY_wiA', 'Sergio Leone', 'Clint Eastwood, Eli Wallach, Lee Van Cleef', 'https://static.metacritic.com/images/products/movies/8/f9c97d56f2abef3d68e94a731a84b3b5.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(13, 'Fight Club', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.
', 'Drama', '8,8/10', 'qtRKdVHc-cE', 'David Fincher', 'Brad Pitt, Edward Norton, Meat Loaf', 'https://aws.boxofficebuz.com/movies/images/fight-club.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(14, 'The Lord of the Rings: The Fellowship of the Ring', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.
', 'Adventure, Drama, Fantasy', '8,8/10', 'V75dMMIW2B4', 'Peter Jackson', 'Elijah Wood, Ian McKellen, Orlando Bloom', 'https://shopstyleblanc.club/wp-content/uploads/2018/10/extra-large-mens-rings-elegant-the-lord-of-the-rings-the-fellowship-of-the-ring-2001-imdb-of-extra-large-mens-rings.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(15, 'Forrest Gump', 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.
', 'Drama, Romance', '8,8/10', 'bLvqoHBptjg', 'Robert Zemeckis', 'Tom Hanks, Robin Wright, Gary Sinise', 'https://i.pinimg.com/originals/fd/77/f2/fd77f2d6e61c16dba1fde055bc6bf67e.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(16, 'Inception ', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.
', 'Action, Adventure, Sci-Fi', '8,8/10', 'YoHD9XEInc0', 'Christopher Nolan', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page', 'https://hips.hearstapps.com/cjp.h-cdn.co/assets/17/37/512010.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(17, 'Star Wars: Episode V - The Empire Strikes Back', 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy
', 'Action, Adventure, Fantasy', '8,7/10', 'Dea4bypvgao', 'Irvin Kershner', 'Mark Hamill, Harrison Ford, Carrie Fisher', 'https://de.lianmovie2.pw/images/covermid/0080684_mid.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(18, 'The Lord of the Rings: The Two Towers', 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron''s new ally, Saruman, and his hordes of Isengard.
', 'Adventure, Drama, Fantasy', '8,7/10', 'LbfMDwc4azU', 'Peter Jackson', 'Elijah Wood, Ian McKellen, Viggo Mortensen', 'https://thefridacinema.org/wp-content/uploads/2019/08/the-lord-of-the-rings-towers_poster-683x1024.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(19, 'The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.
', 'Action, Sci-Fi', '8,7/10', 'm8e-FF8MsqU', 'The Wachowski Brothers', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 'https://www.watson.ch/imgdb/abdd/Qx,E,0,0,665,1000,277,416,110,166/8553749239201866', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(20, 'Goodfellas', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.
', 'Biography, Crime, Drama', '8,7/10', 'ilzidi_J8Q', 'Martin Scorsese', 'Robert De Niro, Ray Liotta, Joe Pesci', 'https://offscreenreviews.files.wordpress.com/2019/03/mv5by2nkzjezmdgtn2rjyy00yzm1lwi4zmqtmjiwyjfjnmi3zgewxkeyxkfqcgdeqxvynzkwmjq5nzm40._v1_.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(21, 'One Flew Over the Cuckoo''s Nest', 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.
', 'Drama', '8,7/10', 'OXrcDonY-B8', 'Milos Forman', 'Jack Nicholson, Louise Fletcher, Will Sampson', 'https://pbs.twimg.com/media/DL3leXRXkAAMElJ.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(22, 'Shichinin no samurai', 'A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.
', 'Action, Adventure, Drama', '8,6/10', 'wJ1TOratCTo', 'Akira Kurosawa', 'Toshirô Mifune, Takashi Shimura, Keiko Tsushima', 'https://m.media-amazon.com/images/M/MV5BODdlYjU1Y2MtMWUxMy00YjJjLTgyMWItNzgzZmZkNTYxNWFkXkEyXkFqcGdeQXVyMTAwMjU1MzA2._V1_UX182_CR0,0,182,268_AL_.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(23, 'Se7en', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.
', 'Crime, Drama, Mystery ', '8,6/10', 'znmZoVkCjpI', 'David Fincher', 'Morgan Freeman, Brad Pitt, Kevin Spacey', 'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(24, 'City of God', 'In the slums of Rio, two kids'' paths diverge as one struggles to become a photographer and the other a kingpin.
', 'Crime, Drama', '8,6/10', 'dcUOO4Itgmw', 'Fernando Meirelles', 'Alexandre Rodrigues, Leandro Firmino, Matheus Nachtergaele', 'https://m.media-amazon.com/images/M/MV5BNDJiNTEwMjMtOGQ1ZC00OTczLWFjZjctZWQ0MGJjZmFkMjcwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg', NULL, NULL, NULL);
INSERT INTO public.movies (id, "name", description, genre, rating, trailer, director, stars, poster, background, streaming, category) VALUES(25, 'Life is Beautiful', 'When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.
', 'Comedy, Drama, Romance ', '8,6/10', 'pAYEQP8gx3w', 'Roberto Benigni', 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini', 'https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg', NULL, NULL, NULL);

--Categories
INSERT INTO public.categories (id, "name", description, menu) VALUES(1, 'Action', 'Action film is a film genre in which the protagonist or protagonists are thrust into a series of events that typically include violence, extended fighting, physical feats, and frantic chases.', true);
INSERT INTO public.categories (id, "name", description, menu) VALUES(2, 'Adventure ', 'Adventure fiction is fiction that usually presents danger, or gives the reader a sense of excitement.
', true);
INSERT INTO public.categories (id, "name", description, menu) VALUES(4, 'Horror ', 'Horror is a genre of speculative fiction which is intended to frighten, scare, disgust, or startle its readers by inducing feelings of horror and terror.', true);
INSERT INTO public.categories (id, "name", description, menu) VALUES(3, 'Romance', 'Two basic elements comprise every romance novel: a central love story and an emotionally satisfying and optimistic ending. ', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(5, 'Animation', 'Animation is a method in which pictures are manipulated to appear as moving images. In traditional animation, images are drawn or painted by hand on transparent celluloid sheets to be photographed and exhibited on film.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(6, 'Biography', 'A film that tells the story of the life of a real person, often a monarch, political leader, or artist. ', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(7, 'Comedy', 'A comedy film is a genre of film in which the main emphasis is on humor. These films are designed to make the audience laugh through amusement and most often work by exaggerating characteristics for humorous effect.', true);
INSERT INTO public.categories (id, "name", description, menu) VALUES(8, 'Crime', 'Crime films, in the broadest sense, are a cinematic genre inspired by and analogous to the crime fiction literary genre. Films of this genre generally involve various aspects of crime and its detection.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(9, 'Documentary', 'A documentary film is a nonfictional motion picture intended to document reality, primarily for the purposes of instruction, education, or maintaining a historical record.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(10, 'Drama', 'In film and television, drama is a genre of narrative fiction (or semi-fiction) intended to be more serious than humorous in tone.', true);
INSERT INTO public.categories (id, "name", description, menu) VALUES(11, 'Family', 'Family film is a genre that is contains appropriate content for younger viewers. Family film aims to appeal not only to children, but to a wide range of ages. ', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(12, 'Fantasy', 'Fantasy films are films that belong to the fantasy genre with fantastic themes, usually magic, supernatural events, mythology, folklore, or exotic fantasy worlds.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(13, 'Film Noir', 'Film noir is a cinematic term used primarily to describe stylish Hollywood crime dramas, particularly those that emphasize cynical attitudes and sexual motivations. The 1940s and 1950s are generally regarded as the "classic period" of American film noir.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(14, 'History', 'A historical film is a fiction film showing past events or set within a historical period. This extensive genre shares territory with the biopic, costume drama, heritage film, and epic film.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(15, 'Horror', 'A horror film is a film that seeks to elicit fear for entertainment purposes.', true);
INSERT INTO public.categories (id, "name", description, menu) VALUES(16, 'Musical', 'Musical film is a film genre in which songs by the characters are interwoven into the narrative, sometimes accompanied by dancing.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(18, 'Mystery', 'A mystery film is a genre of film that revolves around the solution of a problem or a crime.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(19, 'Sci-Fi', 'Science fiction film (or sci-fi film) is a genre that uses speculative, fictional science-based depictions of phenomena that are not fully accepted by mainstream science.', true);
INSERT INTO public.categories (id, "name", description, menu) VALUES(21, 'Sport', 'A sports film is a film genre that uses sport as the theme of the film.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(22, 'Superhero', 'A superhero film, superhero movie or superhero motion picture is a film that is focused on the actions of one or more superheroes: individuals who usually possess superhuman abilities relative to a normal person and are dedicated to protecting the public.', false);
INSERT INTO public.categories (id, "name", description, menu) VALUES(23, 'Thriller', 'Thriller is a genre of fiction, having numerous, often overlapping subgenres. Thrillers are characterized and defined by the moods they elicit, giving viewers heightened feelings of suspense, excitement, surprise, anticipation and anxiety.', true);
INSERT INTO public.categories (id, "name", description, menu) VALUES(24, 'War', 'War film is a film genre concerned with warfare, typically about naval, air, or land battles, with combat scenes central to the drama. It has been strongly associated with the 20th century.', false);